### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by smk** [htmlburger/pixelparallel#1]
Hi!

I'm observing a constant CPU usage of 2-3% in Chrome's Task Manager, even though the extension is not actively used. Which seems abnormally high, given that CPU usage of other Chrome extensions seems to be in the range 0.1-0.5% (on a Macbook Pro 2015).

**Comment by yuliyan** [comment]
Hi @smk,

Thank your for you feedback! Could you please tell us the exact OS and Chrome versions that you are using, so we can reproduce the issue in a similar environment?

**Comment by yuliyan** [comment]
Closing the issue due to inactivity.
