### ISSUE TITLE
Cannot inspect elements through image overlay

### ISSUE THREAD

**Issue by gschoppe** [htmlburger/pixelparallel#2]
One of the more useful scenarios for this plugin is dialing in arbitrary and hard to identify pixel values from a mockup (for example, how many pixels are between two complex curves that don't have clearly delineated bounding boxes). To do so, it would be really nice to be able to inspect and interact with the underlying site without hiding the overlay.

It seems like this would be as simple as adding pointer-events: none; to the overlay image.

**Comment by yuliyan** [comment]
@gschoppe 
You can use the "Lock" button. It will disable the image overlay dragging and it will allow you to click/inspect through the overlay.

**Comment by gschoppe** [comment]
Hi @yuliyan is there a documentation page or help document somewhere that explains this? This is extremely unintuitive to users, as "lock" doesn't imply anything about the click-state of the overlay. As it is, there seems to be a lot of mystery meat functionality.

**Comment by yuliyan** [comment]
@gschoppe,
The "Lock" functionality is somewhat shown in the quick demo video here - https://www.youtube.com/watch?v=tt02nS-cGMI. However, it hasn't been documented in details anywhere yet.
